name: EverShop + testRigor CI

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  evershop-testrigor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
